# Generated by Django 5.2 on 2025-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumption',
            name='food_id',
            field=models.CharField(blank=True, help_text='Food code identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodconsumption',
            name='food_index',
            field=models.IntegerField(default=0, help_text='Index of food in CSV file'),
        ),
    ]
