# Generated by Django 5.2 on 2025-04-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dailygoal_foodconsumption_userdetails_waterintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodconsumption',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterintake',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='FoodConsumption',
        ),
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
